
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESS INSTRUCTION LABEL VAR\n    programa : lista_instrucoes\n             | lista_instrucoes LABEL\n    \n    lista_instrucoes : lista_instrucoes instrucao\n                     | instrucao\n    \n    instrucao : INSTRUCTION VAR ADDRESS\n              | INSTRUCTION VAR VAR\n    '
    
_lr_action_items = {'INSTRUCTION':([0,2,3,6,8,9,],[4,4,-4,-3,-6,-5,]),'$end':([1,2,3,5,6,8,9,],[0,-1,-4,-2,-3,-6,-5,]),'LABEL':([2,3,6,8,9,],[5,-4,-3,-6,-5,]),'VAR':([4,7,],[7,8,]),'ADDRESS':([7,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_instrucoes':([0,],[2,]),'instrucao':([0,2,],[3,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> lista_instrucoes','programa',1,'p_programa','SagaCompiler.py',49),
  ('programa -> lista_instrucoes LABEL','programa',2,'p_programa','SagaCompiler.py',50),
  ('lista_instrucoes -> lista_instrucoes instrucao','lista_instrucoes',2,'p_lista_instrucoes','SagaCompiler.py',59),
  ('lista_instrucoes -> instrucao','lista_instrucoes',1,'p_lista_instrucoes','SagaCompiler.py',60),
  ('instrucao -> INSTRUCTION VAR ADDRESS','instrucao',3,'p_instrucao','SagaCompiler.py',69),
  ('instrucao -> INSTRUCTION VAR VAR','instrucao',3,'p_instrucao','SagaCompiler.py',70),
]
